### ISSUE TITLE
optional image

### ISSUE THREAD

**Issue by skiffb** [sandrods/odf-report#100]
Hello @sandrods,

Thank you for this great gem!

I have been looking into a way to add an optional image to a report that doesn't take up space due to a transparent placeholder when it is not there.

I saw #80 which could remove a section, but it hasn't been merged.

Is there a way to an ad an optional image outside of creating a separate file to be used for it?

Thanks in advance!

**Comment by jirihradil** [comment]
The same issue for me. If I could hide a section programatically, it would be great :)

**Comment by sandrods** [comment]
I'm preparing a new version that removes images if the path is nil
```ruby
r.add_image("IMAGE_01")
r.add_image("IMAGE_02", nil)
```
and also removes sections if the collection is empty/nil

You guys think it will work for you?

**Comment by sandrods** [comment]
Well, 0.7.1 is out and should handle this
