### ISSUE TITLE
Combine documents

### ISSUE THREAD

**Issue by Systho** [sandrods/odf-report#102]
Hello, 

I would very much like to combine multiple documents into a single one.
Either by having a master document with placeholder which can be replaced by other document, or by creating a "blank" document and appending subdocuments one after the other.

My use case is creating "dynamic" reports by choosing programatically what "chunks" must be added and do some placeholder replacement in each of those chunks.

Is this a supported feature ? Can you give me a small example , even in pseudo code , illustrating how to achieve that ? 

Thank you very much in advance !

**Comment by sandrods** [comment]
Sorry, I don't think it's a supported use-case. 
It would require extracting the contents of a ODT file (which is dispersed in multiple xml files) and "transplanting" into another one. That's not an easy task to accomplish.
