### ISSUE TITLE
Nokogiri related memory not freed when `inner_html=` is called

### ISSUE THREAD

**Issue by vanboom** [sandrods/odf-report#117]
https://github.com/sparklemotion/nokogiri/issues/2349#issue-1034492664

Calling `inner_html=` is memory expensive.  

The logic in field.rb should only call `inner_html=` to replace the node contents if a change has been made to the node.  

https://github.com/sandrods/odf-report/blob/16f5b38828d7734fd3e9a72aa1b000384296f7cc/lib/odf-report/field.rb#L22

**Comment by vanboom** [comment]
Yes - gsub will return true if the placeholder is in the document and therefore a substitution is made.  If the placeholder does not exist in the document, there would be no need to replace the inner_html as nothing would be changed.   Thanks for your consideration.

**Comment by vanboom** [comment]
Could you consider my PR please?  I have tested it extensively with over 50,000 documents generated and it is working perfectly. 

Thank you!

**Comment by sandrods** [comment]
I've opted for a slightlly different code, but kept your ideia. thanks for the patience
