### ISSUE TITLE
Example for some simple html-formatting

### ISSUE THREAD

**Issue by dwarfi09** [sandrods/odf-report#124]
Is there any example for formatting via html-tags?

`add_text "<p> first <em>quote paragraph</em> </p>"` adds the paragraph, but the text is not formatted.
`add_field "<em>quote paragraph</em>"` does not render anything.

Thank you!

**Comment by pierre-alain-b** [comment]
I have the same issue: "add_text "<p> first <em>quote paragraph</em> </p>" does not format text.

add_text "<h1> first <em>quote paragraph</em> </h1>"
correctly flags the text with the style "title"

**Comment by pierre-alain-b** [comment]
As a side note, `add_text "<p>first <strong>test</strong> </p>"` does not work either.

For now, I am circumventing the difficulty by using <h1></h1> and setting a style "style" in my document.
Now, this could certainly be made much more interesting if <h1> was calling style1, <h2> was calling style2, etc... this would offer the possibility to inject many styles in the documents. I may propose a pull request if this is welcome.

**Comment by pierre-alain-b** [comment]
See #127 if it seems good enough for merging.

**Comment by sandrods** [comment]
see: https://sandrods.github.io/odf-report/docs/texts
