### ISSUE TITLE
it removes whitespaces inside text

### ISSUE THREAD

**Issue by evgeniy-khatko** [sandrods/odf-report#31]
Please find failing test inside the pull request from me.
Issue details:
1. Try to add text to a document with a lot of white-spaces
2. Look through generated document
Result:
All "extra" white-spaces has been removed during generation
Expected result:
String with white-spaces appears inside generated document as it presented inside the code

**Comment by yokem55** [comment]
If anyone is still looking at this - here is a way to replace strings of more than one consecutive space with a the odf consecutive space tag:
`irb(main):111:0> 'string    with   lots of weird         spacing'.gsub(/ {2,}/){|r| '<text:s text:c=' + r.count(" ").to_s + '/>'}
=> "string<text:s text:c=4/>with<text:s text:c=3/>lots of weird<text:s text:c=9/>spacing"`

I'm guessing this could be put in lib/odf-report/field.rb as a new function along with the sanitize function.
