### ISSUE TITLE
Handle formula objects.

### ISSUE THREAD

**Issue by eloyesp** [sandrods/odf-report#50]
I know that it is not designed for this, but it could be useful to me as I use math formulas that I wanted to generate (to generate exams).

The issue is that formulas are stored within other files (`object 1\content.xml`) and we should change those also.

I've been working a little to see how hard is to implement it, and is not so easy as these two items raised.
- ZipFile is not so well documented so it is not easy to know how to handle multiple files or files in folders on a zip.
- (`object 1\content.xml`) schema is a little different so the image check for name duplication crashes on those files.

My first try is here: https://github.com/eloyesp/odf-report/tree/objects_contents

Thanks.

**Comment by vtamara** [comment]
+1

**Comment by sandrods** [comment]
Sorry, but it's a bit over the scope of this library, and really complex to implement
