### ISSUE TITLE
Error image

### ISSUE THREAD

**Issue by capimoreras** [sandrods/odf-report#52]
I get errors when using images with ODF REPORT. I used libreoffice, and the steps I follow are:
1. Insert any image into the template and put I put the "graphic" name.

Then in my code I have ODF-REPORT:
1. r.add_image ("graphic", File.join (Dir.pwd, 'grafico.png'))

And when I generate the document, I get an error reading the image.

**Comment by marcozimmer** [comment]
Hi,
I have the same problem too...
On MacOS or Raspberry, the images can be seen very well, but on windows, the images do not appear, and the odf file gives me error "Error reading image"

Thank you.
