### ISSUE TITLE
Can I add an image to a section

### ISSUE THREAD

**Issue by ghost** [sandrods/odf-report#6]
Thank you for supporting sections now. I might have missed it, but is it possible to add an image to a section? I see there is no add_image method for sections, as exists for the report. This would be a very important feature for me. Thank you.

**Comment by rmuzzi** [comment]
i think this is curcial to many projects, just realized that it doesn't work in the current version of this gem. Any chance to integrate one of the pull requests? I didn't managed to get them running though :(

**Comment by vanboom** [comment]
+1 for adding images to a table cell
