### ISSUE TITLE
Nested Tags do not work

### ISSUE THREAD

**Issue by vanboom** [sandrods/odf-report#64]
This does not appear to be working... maybe nested tags with the same name are not possible? 

```ruby
report = ODFReport::Report.new("Users/john/my_template.odt") do |r|

  r.add_field :username, @user.name
  r.add_field :address, @user.address

  r.add_table("TABLE_1", @list_of_items, :header=>true) do |t|
    t.add_column(:username, :id)
    t.add_column(:description) { |item| "==> #{item.description}" }
  end

end
```
thanks!

**Comment by sandrods** [comment]
Indeed. Nested tags cannot have the same name as outer tags.


On Thu, Apr 9, 2015 at 11:25 AM, Don <notifications@github.com> wrote:

> This does not appear to be working... maybe nested tags with the same name
> are not possible?
>
> report = ODFReport::Report.new("Users/john/my_template.odt") do |r|
>
> r.add_field :username, @user.name
> r.add_field :address, @user.address
>
> r.add_table("TABLE_1", @list_of_items, :header=>true) do |t|
> t.add_column(:username, :id)
> t.add_column(:description) { |item| "==> #{item.description}" }
> end
>
> end
>
> thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sandrods/odf-report/issues/64>.
>



-- 
Sandro Duarte
Analista de Sistemas
STI/SADES
TRE-RS
