### ISSUE TITLE
feature request: insert unknown number of new images

### ISSUE THREAD

**Issue by blshkv** [sandrods/odf-report#66]
So currently, it is possible to replace an existing image in a template with a new one.
However, it looks more like a hack.

Please create a proper implementation. Documatic used to have that functionality if i'm not wrong.
It should be possible to generate a list of new images from a database and include them in a loop for example.

**Comment by MatthiasWeise** [comment]
I would be interested in that feature too.

**Comment by sandrods** [comment]
Really?

"Your library, which you provided for free, doesn't work like I want and is kinda hack-y. Please do as I say and make a proper implementation of my request."

I don't think you get the gist of open source, but that may be just my perception.

Well, since I don't have the need, the interest nor the time to implement such demand, I'm gonna pass this one.

Pull requests are welcome.

**Comment by MatthiasWeise** [comment]
I am sure it wasn't meant this way. 
It would be interesting to hear your estimate whether it would be either simple (maybe a few lines of code) or more difficult to add. Any thoughts or recommendations?    
Anyway, thanks for making odf-report available!

**Comment by blshkv** [comment]
So you really expect people to contribute to your project after such idiotic statement?
Thank you very much, but I'm not interested in helping you. Good luck with your view on the open community.

**Comment by sandrods** [comment]
@MatthiasWeise, I really don't think it's an easy achievement. Inserting images in a ODT file requires changing multiple files. But I didn't dig really deep into it.

You see, I wasn't even the one who came up with the implementation. It was a pull-request from @joseicosta .

I'm sorry if my last response came out harsh, but I'm not used to be 'demanded' over here. Normally, when people have some need, they either ask politely or they do it themselves.

Anyway, if I can help you to show the way around it, just give me a nod.

**Comment by blshkv** [comment]
Perhaps, it's just a culture difference or a language barrier. There are two sides of the same coin here. I contributed my idea for free (which I only do for open source projects) and was very unhappy to see no appreciation.

Please re-open the ticket and wait for the contribution even if you are not ready to write the code yourself. 

As I mentioned it might be as simple as coping the existing code from https://github.com/TuxmAL/documatic

**Comment by MatthiasWeise** [comment]
What is the status of this pull request: https://github.com/sandrods/odf-report/pull/40 ? 
If images could be replaced per section it would probably solve the proposal from Anton.
