### ISSUE TITLE
Issue with replacing images on Windows

### ISSUE THREAD

**Issue by MatthiasWeise** [sandrods/odf-report#67]
Replacing images failed on Windows due to an issue with zipping files (see: http://stackoverflow.com/questions/10564283/why-are-binary-files-corrupted-when-zipping-them).
To fix this: change the following line of code in images.rb
from 
        file.output_stream.write ::File.read(path)
to
        file.output_stream.write ::File.binread(path)

This solved the issue for me. I havn't yet time double check on Linux whether everything is still correct there.

**Comment by sandrods** [comment]
Was not able to reproduce. It might have been an rubyzip issue. Working allright now
