### ISSUE TITLE
Few templates in common document (template)

### ISSUE THREAD

**Issue by MariaMaria03** [sandrods/odf-report#82]
Can I insert in a single document the results of several templates? Templates are differents. 
Example, begin get 
`report1 = ODFReport::Report.new("path1") do |r| .... end ` and
`report2 = ODFReport::Report.new("path2") do |r| .... end `,
then resulting templates report1, report2 insert in common .odt file (template)?
 If yes, how do it, suggest please?

**Comment by sandrods** [comment]
I'm sorry, but I have no idea how to achieve such functionality.
