### ISSUE TITLE
All mock-images replaced by one (same) image?

### ISSUE THREAD

**Issue by lwnhp** [sandrods/odf-report#89]
In my odt-file I have four mock-images, with four different names (graph1, graph2, graph3, graph4).
In my controller I wish to replace them by four different immages:

`r.add_image :graphd1, "#{Rails.root}/app/assets/images/chart01.png"`
`r.add_image :graphd2, "#{Rails.root}/app/assets/images/chart02.png"`
`r.add_image :graphd3, "#{Rails.root}/app/assets/images/chart03.png"`
`r.add_image :graphd4, "#{Rails.root}/app/assets/images/chart04.png"`

However, the result is dat ALL mock-images are replaced by chart04.png?
The images chart01,02,03,04 are available and are all different.
Is there something I overlooked?
thnx!

**Comment by lwnhp** [comment]
I found it: you cannot use the same mock-image more than once (even when they are duplicated versions, with different filenames). I wonder why?

**Comment by sandrods** [comment]
It was addressed in 0.7.0
