### ISSUE TITLE
Error "no implicit conversion of nil into String (TypeError)" from report.generate

### ISSUE THREAD

**Issue by zx6802** [sandrods/odf-report#91]
Hi.

I get the a traceback as follows

`/var/lib/gems/2.3.0/gems/nokogiri-1.8.1/lib/nokogiri/xml/xpath_context.rb:10:in `register_ns': no implicit conversion of nil into String (TypeError)
	from /var/lib/gems/2.3.0/gems/nokogiri-1.8.1/lib/nokogiri/xml/xpath_context.rb:10:in `block in register_namespaces'
	from /var/lib/gems/2.3.0/gems/nokogiri-1.8.1/lib/nokogiri/xml/xpath_context.rb:8:in `each'
	from /var/lib/gems/2.3.0/gems/nokogiri-1.8.1/lib/nokogiri/xml/xpath_context.rb:8:in `register_namespaces'
	from /var/lib/gems/2.3.0/gems/nokogiri-1.8.1/lib/nokogiri/xml/searchable.rb:191:in `xpath_impl'
	from /var/lib/gems/2.3.0/gems/nokogiri-1.8.1/lib/nokogiri/xml/searchable.rb:179:in `xpath_internal'
	from /var/lib/gems/2.3.0/gems/nokogiri-1.8.1/lib/nokogiri/xml/searchable.rb:154:in `xpath'
	from /var/lib/gems/2.3.0/gems/odf-report-0.5.1/lib/odf-report/images.rb:34:in `avoid_duplicate_image_names'
	from /var/lib/gems/2.3.0/gems/odf-report-0.5.1/lib/odf-report/report.rb:70:in `block (3 levels) in generate'
	from /var/lib/gems/2.3.0/gems/odf-report-0.5.1/lib/odf-report/report.rb:92:in `parse_document'
	from /var/lib/gems/2.3.0/gems/odf-report-0.5.1/lib/odf-report/report.rb:61:in `block (2 levels) in generate'
	from /var/lib/gems/2.3.0/gems/odf-report-0.5.1/lib/odf-report/file.rb:31:in `block (3 levels) in update_files'
	from /var/lib/gems/2.3.0/gems/rubyzip-1.1.7/lib/zip/entry.rb:502:in `get_input_stream'
	from /var/lib/gems/2.3.0/gems/odf-report-0.5.1/lib/odf-report/file.rb:26:in `block (2 levels) in update_files'
	from /var/lib/gems/2.3.0/gems/rubyzip-1.1.7/lib/zip/entry_set.rb:42:in `block in each'
	from /var/lib/gems/2.3.0/gems/rubyzip-1.1.7/lib/zip/entry_set.rb:41:in `each'
	from /var/lib/gems/2.3.0/gems/rubyzip-1.1.7/lib/zip/entry_set.rb:41:in `each'
	from /var/lib/gems/2.3.0/gems/rubyzip-1.1.7/lib/zip/central_directory.rb:182:in `each'
	from /var/lib/gems/2.3.0/gems/odf-report-0.5.1/lib/odf-report/file.rb:22:in `block in update_files'
	from /var/lib/gems/2.3.0/gems/rubyzip-1.1.7/lib/zip/file.rb:99:in `open'
	from /var/lib/gems/2.3.0/gems/odf-report-0.5.1/lib/odf-report/file.rb:20:in `update_files'
	from /var/lib/gems/2.3.0/gems/odf-report-0.5.1/lib/odf-report/report.rb:59:in `block in generate'
	from /var/lib/gems/2.3.0/gems/odf-report-0.5.1/lib/odf-report/file.rb:14:in `block in update_content'
	from /var/lib/gems/2.3.0/gems/rubyzip-1.1.7/lib/zip/output_stream.rb:61:in `write_buffer'
	from /var/lib/gems/2.3.0/gems/odf-report-0.5.1/lib/odf-report/file.rb:12:in `update_content'
	from /var/lib/gems/2.3.0/gems/odf-report-0.5.1/lib/odf-report/report.rb:57:in `generate'
	from /home/*[MYSCRIPTONMYCOMPUTER]*.rb:467:in `<main>'`

Apart from this, the gem is of great help. Thanks a bundle!

Regards Gerald

[template-which-has-issues.odt.zip](https://github.com/sandrods/odf-report/files/1484587/template-which-has-issues.odt.zip)

**Comment by sandrods** [comment]
Sorry for the (really long) delay. Is this still relevant?
